/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestEnviroment;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Window;
import java.awt.image.BufferedImage;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JPanel;

/**
 *
 * @author fabia
 */
public class MainPageCenter extends javax.swing.JPanel {

    
    private DefaultListModel listModel = new DefaultListModel();
    
    private ImageIcon imgPreview = new ImageIcon("C:\\Users\\fabia\\OneDrive\\NeuralNetwork\\NNTest_0.3\\NNtest_21.12\\misc\\img\\noImage.jpg");
    
    private ImageIcon runIdleIcon = new ImageIcon("C:\\Users\\fabia\\OneDrive\\NeuralNetwork\\NNTest_0.3\\NNtest_21.12\\misc\\img\\runNoToggle.png");
    private ImageIcon runToggleIcon = new ImageIcon("C:\\Users\\fabia\\OneDrive\\NeuralNetwork\\NNTest_0.3\\NNtest_21.12\\misc\\img\\runToggle.png");
    
    private ImageIcon uploadIdleIcon = new ImageIcon("C:\\Users\\fabia\\OneDrive\\NeuralNetwork\\NNTest_0.3\\NNtest_21.12\\misc\\img\\imageIcon.png");
    private ImageIcon uploadToggleIcon = new ImageIcon("C:\\Users\\fabia\\OneDrive\\NeuralNetwork\\NNTest_0.3\\NNtest_21.12\\misc\\img\\imageIconToggle.png");
    
    private double previewScale = 0.5;
    /**
     * Creates new form MainPageCenter
     */
    public MainPageCenter() {
        initComponents();
        startUp();
    }
    
    private void startUp(){
        paint(south2, EnvUtils.primColor);
        paint(southPanel, EnvUtils.primColor);
        paint(imageField, EnvUtils.primColor);
        paint(imageContainer, EnvUtils.primColor);
        
        
        updatePreviewImg();
        
        imageField.setBackground(EnvUtils.primColor);
        imageContainer.setBorder(EnvUtils.buttonBorder);
        
        jList1.setBackground(EnvUtils.listColor);
        jList1.setModel(listModel);
    }
    
    private void updatePreviewImg(){
        
        int imgWidth = imgPreview.getIconWidth();
        int imgHeight = imgPreview.getIconHeight();
        
        int newWidth = (int)(imgWidth * previewScale);
        int newHeight = (int)(imgHeight * previewScale);
        
        Image convImage = imgPreview.getImage().getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        image.setIcon(new ImageIcon(convImage));
    }
    
    private static void paint(JComponent comp, Color color){
        for(Component c : comp.getComponents()){
            c.setBackground(color);
        }
        comp.setBackground(color);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageField = new javax.swing.JPanel();
        southPanel = new javax.swing.JPanel();
        northStut = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 10));
        south2 = new javax.swing.JPanel();
        uploadButton = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(10, 32767));
        runButton = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        southStut = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        imageContainer = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        image = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        imageProperties = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setLayout(new java.awt.BorderLayout());

        imageField.setToolTipText("");
        imageField.setLayout(new java.awt.BorderLayout());

        southPanel.setLayout(new java.awt.BorderLayout());
        southPanel.add(northStut, java.awt.BorderLayout.NORTH);

        uploadButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabia\\OneDrive\\NeuralNetwork\\NNTest_0.3\\NNtest_21.12\\misc\\img\\imageIcon.png")); // NOI18N
        uploadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                uploadButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                uploadButtonMouseReleased(evt);
            }
        });
        south2.add(uploadButton);
        south2.add(filler2);

        runButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabia\\OneDrive\\NeuralNetwork\\NNTest_0.3\\NNtest_21.12\\misc\\img\\runNoToggle.png")); // NOI18N
        runButton.setMaximumSize(new java.awt.Dimension(50, 50));
        runButton.setPreferredSize(new java.awt.Dimension(65, 65));
        runButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                runButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                runButtonMouseReleased(evt);
            }
        });
        south2.add(runButton);
        south2.add(filler1);

        southPanel.add(south2, java.awt.BorderLayout.CENTER);
        southPanel.add(southStut, java.awt.BorderLayout.SOUTH);

        imageField.add(southPanel, java.awt.BorderLayout.SOUTH);

        imageContainer.setMinimumSize(new java.awt.Dimension(360, 129));
        imageContainer.setPreferredSize(new java.awt.Dimension(360, 129));
        imageContainer.setLayout(new java.awt.BorderLayout());
        imageContainer.add(filler3, java.awt.BorderLayout.NORTH);

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setPreferredSize(new java.awt.Dimension(360, 100));
        imageContainer.add(image, java.awt.BorderLayout.CENTER);
        imageContainer.add(filler4, java.awt.BorderLayout.SOUTH);

        imageField.add(imageContainer, java.awt.BorderLayout.CENTER);

        add(imageField, java.awt.BorderLayout.CENTER);

        imageProperties.setBorder(null);
        imageProperties.setMinimumSize(new java.awt.Dimension(50, 50));

        jList1.setPreferredSize(new java.awt.Dimension(75, 90));
        imageProperties.setViewportView(jList1);

        add(imageProperties, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    
    private void runButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runButtonMousePressed
        runButton.setIcon(runToggleIcon);
    }//GEN-LAST:event_runButtonMousePressed

    private void runButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runButtonMouseReleased
        runButton.setIcon(runIdleIcon);
    }//GEN-LAST:event_runButtonMouseReleased

    private void uploadButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadButtonMousePressed
        uploadButton.setIcon(uploadToggleIcon);
    }//GEN-LAST:event_uploadButtonMousePressed

    private void uploadButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadButtonMouseReleased
        uploadButton.setIcon(uploadIdleIcon);
    }//GEN-LAST:event_uploadButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel image;
    private javax.swing.JPanel imageContainer;
    private javax.swing.JPanel imageField;
    private javax.swing.JScrollPane imageProperties;
    private javax.swing.JList<String> jList1;
    private javax.swing.Box.Filler northStut;
    private javax.swing.JLabel runButton;
    private javax.swing.JPanel south2;
    private javax.swing.JPanel southPanel;
    private javax.swing.Box.Filler southStut;
    private javax.swing.JLabel uploadButton;
    // End of variables declaration//GEN-END:variables

    public void increaseScale(){
        if(previewScale < 1){
            previewScale += 0.1;
        }
    }
    
    public void decreaseScale(){
        if(previewScale > 0.2){
            previewScale -= 0.1;
        }
    }
    
    public void refresh(){
        updatePreviewImg();
        repaint();
    }
}
